name: kiosk_flutter
description: Munchies Kiosk port from Android to Flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.19.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8 
  provider: ^6.1.2 
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  # web_socket_channel: ^2.2.0
  # lottie: ^1.4.3
  # rive: ^0.9.1
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.3
  geolocator: ^12.0.0
  # geocoding: ^2.0.5
  network_info_plus: ^5.0.3
  permission_handler: ^11.3.1
  # flutter_pdfview: ^1.2.1
  # flutter_widget_from_html: ^0.9.0
  # sqflite: ^2.2.2
  # path: ^1.8.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.7.0
  # webview_flutter: ^3.0.4
  device_info_plus: ^10.1.0
  # fpjs_pro_plugin: ^1.3.0
  qr_code_scanner: ^1.0.1
  cached_network_image: ^3.3.1
  pay: ^2.0.0
  # mock_web_server: ^5.0.0-nullsafety.1
  # xdg_desktop_portal: ^0.1.12
  # window_manager: ^0.3.4
  just_audio: ^0.9.34
  # just_audio_mpv: ^0.1.6
  dio: ^5.3.2
  supabase_flutter: ^2.0.0
  http: ^1.2.1
  async: ^2.11.0
  webview_flutter: ^4.8.0
  uuid: ^4.4.2

  # payu:
  #   git:
  #     url: https://github.com/PayU-EMEA/PayU-Flutter.git
  #     path: payu
  #     ref: 1.0.2


dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  #  integration_test:
  #    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/MuchiesLogoPlain.svg
    - assets/images/background.svg
    - assets/images/angFlag.svg
    - assets/images/polandFlag.svg
    - assets/images/touch.svg
    - assets/Logo.png
    - assets/images/robotAnimation/robot_frame_1.svg
    - assets/images/robotAnimation/robot_frame_2.svg
    - assets/images/robotAnimation/robot_frame_3.svg
    - assets/images/robotAnimation/robot_frame_4.svg
    - assets/images/robotAnimation/robot_frame_6.svg
    - assets/images/robotAnimation/robot_frame_7.svg
    - assets/images/robotAnimation/robot_frame_8.svg
    - assets/images/robotAnimation/orderMenuRobot/new_robot_arms.svg
    - assets/images/robotAnimation/orderMenuRobot/new_robot_back.svg
    - assets/images/robotAnimation/orderMenuRobot/newRobotArms.png
    - assets/images/robotAnimation/orderMenuRobot/newRobotBack.png
    - assets/images/flagOfPoland.png
    - assets/images/plFlag.png
    - assets/images/angFlag.png
    - assets/animations/robotTest.json
    - assets/animations/robot1.riv
    - assets/animations/robotArms.riv
    - assets/animations/robotBack.riv
    - assets/animations/newBody.riv
    - assets/animations/newArms.riv
    - assets/data/countries.json
    - assets/images/robotAnimation/orderMenuRobot/newRobotBeg.png
    - assets/images/payULogos/payULogoBlack.png
    - assets/images/payULogos/payULogoLime.png
    - assets/images/payULogos/payULogoWhite.png
    - assets/Regulamin.pdf
    - assets/sounds/beep.mp3
    - assets/audio/

  fonts:
    - family: GloryBold
      fonts:
        - asset: assets/fonts/Glory-Bold.ttf
    - family: GloryExtraBold
      fonts:
        - asset: assets/fonts/Glory-ExtraBold.ttf
    - family: GloryLight
      fonts:
        - asset: assets/fonts/Glory-Light.ttf
    - family: GloryLightItalic
      fonts:
        - asset: assets/fonts/Glory-LightItalic.ttf
    - family: GloryMedium
      fonts:
        - asset: assets/fonts/Glory-Medium.ttf
    - family: GloryMediumItalic
      fonts:
        - asset: assets/fonts/Glory-MediumItalic.ttf

flutter_intl:
  enabled: true
  class_name: AppText
  arb_dir: lib/l10n
  output_dir: lib/l10n/generated
  template_arb_file: app_en.arb
