name: munchies-kiosk
version: 0.1.0
summary: Munchies Kiosk
description: Munchies Kiosk App

confinement: strict
base: core20
grade: stable

apps:
  munchies-kiosk:
    command: kiosk_frontend
    extensions: [flutter-stable]
    plugs:
      - network
      - desktop
      - desktop-legacy
      - x11
      - wayland
      - gsettings
      - unity7
      - audio-playback
      - audio-record
      - pulseaudio
      - alsa

parts:
  flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart


